### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cyrodjohn** [xcesaralejandro/lti1p3#4]
Do you have some sort of wiki on how to use?

**Comment by xcesaralejandro** [comment]
I've put this project aside for work. It is fully functional for LTI 1.3. Not so LTI Advantage (Although there is a branch that is capable of obtaining the token for said service. More not code encapsulated as facades).

There is a brief description to understand how the roles work. I understand that without proper documentation it is difficult to implement for new people and reviewing the code can take a lot of time.

I hope this weekend I can start with better documentation, but to be more helpful, could you tell me what is most critical for you to know right now.

Implementation / Configuration? ; Launching? How to start developing?


Sorry for my English, I used the translator :D

**Comment by cyrodjohn** [comment]
Hello. Thanks for the reply. I appreciate it.

I'm playing around with the code and checking if it fits with what i'm looking for (We are adding LTI 1.3 functionality, we are in LTI 1.0).

Maybe i can email you instead if i have any questions?

Thanks!

**Comment by xcesaralejandro** [comment]
Sure, feel free to contact me. As long as I know the answer I will help you. If not, I might be able to help you find a solution.

Anyway, if you think it's a query that can help someone else in the future, you could leave it as an issue, it's not easy for any developer to understand LTI and the information is somewhat scarce.

**Comment by cyrodjohn** [comment]
Is there a way to pass custom attributes?

**Comment by xcesaralejandro** [comment]
Yes, in the LTI configuration within the LMS. These variables will always be passed for all instances of your LTI, you cannot apply filters and conditions to pass different variables depending on the context (As far as I understand).
This varies depending on the LMS, but many provide variable substitution (not standardized) where the data is converted to contextual.

You can also define your own key-value variables, which you must then retrieve from the initial LTI launch object (where the resource link, user data, etc.)

I found this cheat sheet to quick variable substitution for the LMS Canvas:
[https://gist.github.com/jbasdf/15fb8abed66fbaf623cdfbdd45bfb1c4](https://gist.github.com/jbasdf/15fb8abed66fbaf623cdfbdd45bfb1c4)

If you need to serve contextual and custom variables that are not within your LMS's variable substitution, you can handle these values as a setting within your LTI. In the first launch check if there is a configuration for your resourcelink and/or course, if not, force the user with the corresponding role to enter the configuration with the necessary parameters to continue.

You can keep a default configuration or block with some screen like "We are configuring the resource" for roles that are waiting.

**Comment by cyrodjohn** [comment]
I'm trying to figure out how to do grade push (line items) - i saw the lti advantage branch. Is that a good place to start?

**Comment by xcesaralejandro** [comment]
That branch only remained in the intention. But it has a code snippet that will allow you to understand how to obtain a valid token and then consume the lti avantage endpoints. In fact, the example uses the names and roles service to obtain such information.

In the `Lti1p3Controller` -  `Nrps::init($instance);` this is a facade and its class is in `lti1p3/src/Classes/Nrps.php` ; We can notice that it extends to service that is in the same location.

First of all, the method has all the code to consume the service, it was in the testing context. My intention was to encapsulate the core in the service class to later have a facade for the name and role services and notes, reusing what is common within the service class (Obtaining the token and consuming the webservices).

Then simply structure the provided results into classes with friendly methods.

As a bonus, you may notice that the URL to get the token is different, this should be provided by the LMS documentation and when we add an instance, we should add this url there.

Another project in PHP that helped guide me and in fact the author solved some doubts (which I really appreciate). It is the following:
[https://github.com/celtic-project/LTI-PHP](https://github.com/celtic-project/LTI-PHP)

The problem with it is that it mixed LTI 1.1 ; 1.0 ; 1.3; Making it hard to understand some things.

**Comment by cyrodjohn** [comment]
Awesome! I'll check it out. Once again thanks for the detailed reply

**Comment by cyrodjohn** [comment]
Hello. Is the LTI Advantage branch working?

**Comment by xcesaralejandro** [comment]
No, it is outdated. The main branch brings improvements and is better adapted to what the standard says. Also now supports LTI Deep Linking.

I still keep the advantage branch because they have a working example to consume the services in moodle and maybe in other LMS. After that, the LMS response would have to be encapsulated in more manageable classes.

The problem is in Canvas LMS, some things don't work as expected and it's hard to get answers from the company. Just a few months ago they fixed some errors but the generation of tokens to consume adventage services does not work.
If you are using CanvasLMS I recommend you to complement with the package to integrate Oauth2 (canvasoauth) and consume the canvas API which will allow you to do the same thing as adventage and much more (combining the best of both worlds).
lti1p3 and canvasoauth work well together, plus you can extend classes or override methods at any time after publishing the vendor.

In practice, forget about the adventage branch as functional for now, just use them as a reference to consume the service (in moodle), to understand better, check the following file that has the only thing salvageable from that whole branch:


https://github.com/xcesaralejandro/lti1p3/blob/lti_advantage_test/src/Classes/Nrps.php


You can tell me the LMS is working to better help you, even though LTI is a standard LMSs often add their own flavor to the standard by doing a few different things. 
I have particularly worked with moodle and canvas, if you are using another we could talk to be able to integrate the package and be able to solve possible errors, I work on this for my free time, it is for the love of art.

**Comment by cyrodjohn** [comment]
I'm still trying to understand the flow. I am more interested with grade passback. Where do you think is a good place to start?

**Comment by xcesaralejandro** [comment]
First, you must understand that you cannot use LTI Advantage (Ratings Service) without first using "regular" LTI.
That is, it requires creating an LTI to launch your application under the standard and then consume the extra services, which should not be more complex than exchanging credentials and consuming a webservice. (The respective endpoints should come in the original LTI message).

Depending on the LMS you will be able to configure your LTI in different sections, for example: the course menu, a module resource, etc. There may be locations where the LMS limits the ratings service, try to start by setting your LTI to a location that should obviously be able to rate, such as a resource.

What I will say now may confuse you a bit, once you have an LTI message and store the respective data, you could consume the ratings service from your application without the need of an LTI launch (being outside of the LMS). This would be possible because you will have stored the respective data to consume the service, this will depend a little on the business model that your application implements and the technical solution that you use, I will tell you so that you know that it is possible.

Please note that for security reasons the ratings service is limited, this means that it works in its respective context. In other words, you will only be able to manage the rating of your tool instance (Add, View, Modify, etc.) you will not have access to other LMS ratings.

Where to start?

The first thing is to decide if you want to use this or another package, or build your own code from scratch.

If you want to build your code from scratch, go see the documentation for the LTI standard and LTI Advantage. Although it is somewhat confusing to understand, no one better than the creators of the standard to tell you how to do things.

If you want to use a package, possibly integrating is easier and you only have to configure things. This package as of today will fix all LTI integration, but does not yet have support for LTI Advantage. Being developed for Laravel, it has all the advantages of this framework.

I have not yet implemented LTI Advantage (which allows to obtain the list of members of a course and manage grades) to this package because it does not work properly for all LMS (differences from LMS to follow the standard).

If you use moodle, the consumption example I mentioned above should be enough to understand (with reverse engineering) how to consume an LTI Advantage service, if you use canvas, better combine the current LTI package with the Canvas Oauth package to work with the Canvas API.

If you are using another LMS, I have not tested its integration, if you manage to give me access to an account as a teacher, I could test the integration and correct possible exceptions.

Lately my work life consumes me, daily work, extra projects, all this to survive in Latin America. Although my time is limited lately I think I could help you in a better way, maybe with a step by step video of how to start with the development/configuration or something like that, but I need to know what LMS you are working on so that everything works properly.

**Comment by xcesaralejandro** [comment]
Inactivity

**Comment by xcesaralejandro** [comment]
Inactivity
